<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Student;
use App\Models\School;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $schools = School::all();

        if ($schools->isEmpty()) {
            $this->command->warn('Nenhuma escola encontrada. Execute primeiro o SchoolSeeder.');
            return;
        }

        $students = [
            [
                'name' => 'Ana Carolina Silva Santos',
                'email' => 'ana.carolina@email.com',
                'phone' => '11987654321',
                'cpf' => '12345678901',
                'rg' => '123456789',
                'birth_date' => '2010-03-15',
                'gender' => 'feminino',
                'enrollment' => 'ANA2024001',
                'school_id' => $schools->where('name', 'like', '%João Silva%')->first()?->id ?? $schools->first()->id,
                'grade' => '8º ano',
                'class' => 'A',
                'school_year' => 2024,
                'status' => 'ativo',
                'street' => 'Rua das Palmeiras',
                'number' => '123',
                'complement' => 'Apto 45',
                'neighborhood' => 'Jardim Paulista',
                'city' => 'São Paulo',
                'state' => 'SP',
                'postal_code' => '01451000',
                'country' => 'Brasil',
                'guardian_name' => 'Maria Silva Santos',
                'guardian_phone' => '11987654322',
                'guardian_email' => 'maria.santos@email.com',
                'guardian_cpf' => '98765432100',
                'guardian_relationship' => 'mae',
                'medical_info' => 'Alergia a amendoim',
                'observations' => 'Aluna dedicada e participativa',
                'enrollment_date' => '2024-02-01',
            ],
            [
                'name' => 'João Pedro Oliveira Lima',
                'email' => 'joao.pedro@email.com',
                'phone' => '21987654321',
                'cpf' => '23456789012',
                'rg' => '234567890',
                'birth_date' => '2008-07-22',
                'gender' => 'masculino',
                'enrollment' => 'JOA2024002',
                'school_id' => $schools->where('name', 'like', '%Santa Maria%')->first()?->id ?? $schools->skip(1)->first()->id,
                'grade' => '1º ano',
                'class' => 'B',
                'school_year' => 2024,
                'status' => 'ativo',
                'street' => 'Avenida Atlântica',
                'number' => '456',
                'complement' => null,
                'neighborhood' => 'Copacabana',
                'city' => 'Rio de Janeiro',
                'state' => 'RJ',
                'postal_code' => '22070000',
                'country' => 'Brasil',
                'guardian_name' => 'Carlos Oliveira Lima',
                'guardian_phone' => '21987654322',
                'guardian_email' => 'carlos.lima@email.com',
                'guardian_cpf' => '87654321009',
                'guardian_relationship' => 'pai',
                'medical_info' => null,
                'observations' => 'Bom desempenho em matemática',
                'enrollment_date' => '2024-01-15',
            ],
            [
                'name' => 'Beatriz Costa Ferreira',
                'email' => 'beatriz.costa@email.com',
                'phone' => '31987654321',
                'cpf' => '34567890123',
                'rg' => '345678901',
                'birth_date' => '2005-11-08',
                'gender' => 'feminino',
                'enrollment' => 'BEA2024003',
                'school_id' => $schools->where('name', 'like', '%Instituto Federal%')->first()?->id ?? $schools->skip(2)->first()->id,
                'grade' => '3º ano',
                'class' => 'A',
                'school_year' => 2024,
                'status' => 'ativo',
                'street' => 'Rua dos Inconfidentes',
                'number' => '789',
                'complement' => 'Casa',
                'neighborhood' => 'Centro',
                'city' => 'Belo Horizonte',
                'state' => 'MG',
                'postal_code' => '30112000',
                'country' => 'Brasil',
                'guardian_name' => 'Ana Costa Ferreira',
                'guardian_phone' => '31987654322',
                'guardian_email' => 'ana.ferreira@email.com',
                'guardian_cpf' => '76543210008',
                'guardian_relationship' => 'mae',
                'medical_info' => 'Usa óculos para miopia',
                'observations' => 'Interesse em cursos técnicos',
                'enrollment_date' => '2024-02-05',
            ],
            [
                'name' => 'Lucas Henrique Souza',
                'email' => null,
                'phone' => '61987654321',
                'cpf' => '45678901234',
                'rg' => '456789012',
                'birth_date' => '2003-01-30',
                'gender' => 'masculino',
                'enrollment' => 'LUC2024004',
                'school_id' => $schools->where('name', 'like', '%Universidade%')->first()?->id ?? $schools->skip(3)->first()->id,
                'grade' => '1º período',
                'class' => null,
                'school_year' => 2024,
                'status' => 'ativo',
                'street' => 'Quadra 10 Conjunto A',
                'number' => '15',
                'complement' => 'Casa 2',
                'neighborhood' => 'Asa Norte',
                'city' => 'Brasília',
                'state' => 'DF',
                'postal_code' => '70910000',
                'country' => 'Brasil',
                'guardian_name' => 'Roberto Souza',
                'guardian_phone' => '61987654322',
                'guardian_email' => 'roberto.souza@email.com',
                'guardian_cpf' => '65432100007',
                'guardian_relationship' => 'pai',
                'medical_info' => null,
                'observations' => 'Bolsista de iniciação científica',
                'enrollment_date' => '2024-03-01',
            ],
            [
                'name' => 'Mariana Santos Almeida',
                'email' => 'mariana.almeida@email.com',
                'phone' => '11912345678',
                'cpf' => '56789012345',
                'rg' => '567890123',
                'birth_date' => '2017-05-12',
                'gender' => 'feminino',
                'enrollment' => 'MAR2024005',
                'school_id' => $schools->where('name', 'like', '%EMEI%')->first()?->id ?? $schools->skip(4)->first()->id,
                'grade' => 'Pré II',
                'class' => 'B',
                'school_year' => 2024,
                'status' => 'ativo',
                'street' => 'Rua das Flores',
                'number' => '321',
                'complement' => null,
                'neighborhood' => 'Vila Esperança',
                'city' => 'São Paulo',
                'state' => 'SP',
                'postal_code' => '08460000',
                'country' => 'Brasil',
                'guardian_name' => 'Patricia Santos Almeida',
                'guardian_phone' => '11912345679',
                'guardian_email' => 'patricia.almeida@email.com',
                'guardian_cpf' => '54321000006',
                'guardian_relationship' => 'mae',
                'medical_info' => 'Acompanhamento fonoaudiológico',
                'observations' => 'Criança muito sociável',
                'enrollment_date' => '2024-02-15',
            ],
            [
                'name' => 'Gabriel Rodrigues Costa',
                'email' => 'gabriel.costa@email.com',
                'phone' => '47987654321',
                'cpf' => '67890123456',
                'rg' => '678901234',
                'birth_date' => '2006-09-18',
                'gender' => 'masculino',
                'enrollment' => 'GAB2024006',
                'school_id' => $schools->where('name', 'like', '%Técnico%')->first()?->id ?? $schools->first()->id,
                'grade' => '2º ano',
                'class' => 'A',
                'school_year' => 2024,
                'status' => 'transferido',
                'street' => 'Rua Industrial',
                'number' => '555',
                'complement' => 'Bloco B',
                'neighborhood' => 'Centro Industrial',
                'city' => 'Joinville',
                'state' => 'SC',
                'postal_code' => '89201000',
                'country' => 'Brasil',
                'guardian_name' => 'José Rodrigues Costa',
                'guardian_phone' => '47987654322',
                'guardian_email' => 'jose.costa@email.com',
                'guardian_cpf' => '43210000005',
                'guardian_relationship' => 'pai',
                'medical_info' => null,
                'observations' => 'Transferido para outra cidade por motivo familiar',
                'enrollment_date' => '2024-01-20',
            ],
        ];

        foreach ($students as $studentData) {
            Student::create($studentData);
        }
    }
}
